linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exhaustruct
  - exportloopref
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - ireturn
  - loggercheck
  - makezero
  - mirror
  - misspell
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  - wrapcheck
  - zerologlint
  disable:
  - cyclop
  - depguard
  - forbidigo
  - funlen
  - gochecknoglobals
  - godox
  - gomnd
  - lll
  - maintidx
  - nlreturn
  - paralleltest
  - testableexamples
  - testpackage
  - varnamelen
  - wsl

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-shell)
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/go-shell
  goimports:
    local-prefixes: github.com/twpayne/go-shell
