name: Test
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - stable
        - oldstable
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
      with:
        version: v1.54.2
